name 'puppet-pushover'
version '0.0.1'
license 'Apache 2.0'
summary 'Report processor that notifies Pushover channel about failed Puppet runs'
project_page 'https://github.com/jamtur01/puppet-pushover'
